### PR TITLE
Fixed the calculation of the quartiles.

### PR DESCRIPTION
**Pull request by clody69**
Fixed the calculation of the quartiles.

### CODE REVIEW

**Comment by gwatts** [comment]
Sorry this has taken so long to get to, however it doesn't appear that your update fixes the issue.

There seems to be no universally accepted way of calculating quartiles, however given the inputs [10,20,30,40,50] i'd expect q1,q2,q3 to come out as [20,30,40] and given the input [10,20,30,40] i'd expect [15,25,35].

With your update I get [15,30,35] and [20,25,40] respectively

Care to take another pass (please open a new pull request, if so)?

**Comment by clody69** [comment]
You are right. I was mainly fixing the median but I didn't test carefully the quartiles. I did some research how to calculate the quartiles and I agree with you there isn't an universally accepted way. I've found this good summary: http://mathworld.wolfram.com/Quartile.html

I think the method Moore and McCabe (2002) gives the best result. In the case the quartile is a cut between two numbers we can use the average of the two numbers (like for the median).

Here is the implementation in javascript. Could you please test it and if it's ok I can update the pull request. 

``` javascript
quartile = function (values, q) {
        var vl;
        if (q === 2) {
            vl = Math.floor(values.length / 2);
            return values.length % 2 ? values[vl] : (values[vl-1] + values[vl ]) / 2;
        } else {
            if (values.length % 2 )
            { // odd
                vl = (values.length * q + q) / 4;
                return vl % 1 ? (values[Math.floor(vl)] + values[Math.floor(vl) - 1]) / 2 : values[vl-1] ;
            } else
            { //even
                vl = (values.length * q + 2) / 4;
                return vl % 1 ? (values[Math.floor(vl)] + values[Math.floor(vl) - 1]) / 2 :  values[vl-1];

            }
        }
    };
```

Some tests: 

``` javascript
quartile( [1,2,3,4,5], 1)
1.5
quartile( [1,2,3,4,5], 3)
4.5
quartile( [1,2,3,4,5,6], 1)
2
quartile( [1,2,3,4,5,6], 3)
5
quartile( [1,2,3,4,5,6,7], 1)
2
quartile( [1,2,3,4,5,6,7], 3)
6
quartile( [1,2,3,4,5,6,7,8], 1)
2.5
quartile( [1,2,3,4,5,6,7,8], 3)
6.5
quartile( [10,20,30,40,50], 1)
15
quartile( [10,20,30,40,50], 3)
45
quartile( [10,20,30,40], 1)
15
quartile( [10,20,30,40], 3)
35
```

**Comment by gwatts** [comment]
Thanks for doing the research - I think that looks good - If you could create a new pull request with that change, that would be preferred so we end up with a single commit in the history rather than two

Style comment: Please use the same brace style as the rest of the file - opening braces on the same line as the if/else statement

**Comment by gwatts** [comment]
Manually merged into master as commit ae34cb368d1344a3ff5dbd13b4aa105a5e4bbc3c

**Pull request closed without merging**
